regsvr32/u "c:\nt-spb\probeam\NL3FB.dll"
regsvr32/u "c:\nt-spb\probeam\NL3LFB.dll"
regsvr32/u "c:\nt-spb\probeam\MLPC_API.dll"
regsvr32/u "c:\nt-spb\probeam\MLPC_API2.dll"
regsvr32/u "c:\nt-spb\probeam\NL3Cntx.dll"
regsvr32/u "c:\nt-spb\probeam\SiGraph.dll"
