regsvr32/u "c:\nt-spb\nanotutor\NL3FB.dll"
regsvr32/u "c:\nt-spb\nanotutor\NL3LFB.dll"
regsvr32/u "c:\nt-spb\nanotutor\MLPC_API.dll"
regsvr32/u "c:\nt-spb\nanotutor\MLPC_API2.dll"
regsvr32/u "c:\nt-spb\nanotutor\NL3Cntx.dll"
regsvr32/u "c:\nt-spb\nanotutor\SiGraph.dll"
